name: Deploy to EKS

on:
  push:
    branches: [ main ]
    paths:
      - 'terraform/**'
      - 'app/**'
      - 'helm/**'
      - '.github/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    # for create tags in github
    permissions:
      contents: write
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: '0' # for read the history of tags
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}
    
    # --- Terraform ---
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2

    - name: Terraform Init & Apply
      run: |
        terraform init
        terraform apply -auto-approve -no-color
      working-directory: ./terraform

    # --- Tags Manger ---
    - name: Bump version and push tag
      id: tag_version
      uses: anothrNick/github-tag-action@1.64.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        INITIAL_VERSION: 1.0.0
        DEFAULT_BUMP: patch # up the last number in the tag (default)
        WITH_V: false
    
    # --- Docker: Build&Push ---
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Check if image exists in ECR
      id: check-image
      env:
        ECR_REPOSITORY: flask-app-repo
        IMAGE_TAG: ${{ steps.tag_version.outputs.new_tag }}
      run: |
        if aws ecr describe-images --repository-name $ECR_REPOSITORY --image-ids imageTag=$IMAGE_TAG > /dev/null 2>&1; then
          echo "exists=true" >> $GITHUB_OUTPUT
        else
          echo "exists=false" >> $GITHUB_OUTPUT
        fi

    - name: Build, tag, and push image
      if: steps.check-image.outputs.exists != 'true'
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: flask-app-repo
        IMAGE_TAG: ${{ steps.tag_version.outputs.new_tag }}
      run: |
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG ./app
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
    
    # --- Helm: Deploy Level ---
    - name: Update kubeconfig
      run: aws eks update-kubeconfig --name devops-assignment-eks --region ${{ secrets.AWS_REGION }}

    - name: Deploy to EKS with Helm
      run: |
        helm upgrade --install my-flask-app ./helm/flask-app \
          --set image.tag=${{ steps.tag_version.outputs.new_tag }} \
          --wait